export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_NOT_LOGGED_IN = "USER_NOT_LOGGED_IN";
export const USER_LOGGING_IN = "USER_LOGGING_IN";
export const USER_LOGGING_OUT = "USER_LOGGING_OUT";
